### ISSUE TITLE
webext internationalization format wants '$' instead of '%'

### ISSUE THREAD

**Issue by meandavejustice** [bwinton/pontoon-to-webext#1]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Direct_placeholder_usage

**Comment by bwinton** [comment]
I'm not sure what the bug here is…  Can you expand on it a little?

**Comment by meandavejustice** [comment]
@bwinton This is not actually an issue, I was thinking about how my initial `.properties` files had `%s` for arguments instead of `$`. But that doesn't really have to do with this code at all; it was just a preference of the addon-sdk. Closing.
